export const SURAHS = [
  { number: 1,   name: "Al-Fatiha",       arabic: "الفاتحة",    ayahs: 7,   juz: [1],       pages: [1,1] },
  { number: 2,   name: "Al-Baqarah",      arabic: "البقرة",      ayahs: 286, juz: [1,2,3],   pages: [2,49] },
  { number: 3,   name: "Al-Imran",        arabic: "آل عمران",    ayahs: 200, juz: [3,4],     pages: [50,76] },
  { number: 4,   name: "An-Nisa",         arabic: "النساء",      ayahs: 176, juz: [4,5,6],   pages: [77,106] },
  { number: 5,   name: "Al-Maidah",       arabic: "المائدة",     ayahs: 120, juz: [6,7],     pages: [107,127] },
  { number: 6,   name: "Al-An'am",        arabic: "الأنعام",     ayahs: 165, juz: [7,8],     pages: [128,150] },
  { number: 7,   name: "Al-A'raf",        arabic: "الأعراف",     ayahs: 206, juz: [8,9],     pages: [151,176] },
  { number: 8,   name: "Al-Anfal",        arabic: "الأنفال",     ayahs: 75,  juz: [9,10],    pages: [177,186] },
  { number: 9,   name: "At-Tawbah",       arabic: "التوبة",      ayahs: 129, juz: [10,11],   pages: [187,207] },
  { number: 10,  name: "Yunus",           arabic: "يونس",        ayahs: 109, juz: [11],      pages: [208,221] },
  { number: 11,  name: "Hud",             arabic: "هود",         ayahs: 123, juz: [11,12],   pages: [221,235] },
  { number: 12,  name: "Yusuf",           arabic: "يوسف",        ayahs: 111, juz: [12,13],   pages: [235,248] },
  { number: 13,  name: "Ar-Ra'd",         arabic: "الرعد",       ayahs: 43,  juz: [13],      pages: [249,255] },
  { number: 14,  name: "Ibrahim",         arabic: "إبراهيم",     ayahs: 52,  juz: [13],      pages: [255,261] },
  { number: 15,  name: "Al-Hijr",         arabic: "الحجر",       ayahs: 99,  juz: [13,14],   pages: [261,267] },
  { number: 16,  name: "An-Nahl",         arabic: "النحل",       ayahs: 128, juz: [14],      pages: [267,281] },
  { number: 17,  name: "Al-Isra",         arabic: "الإسراء",     ayahs: 111, juz: [15],      pages: [282,293] },
  { number: 18,  name: "Al-Kahf",         arabic: "الكهف",       ayahs: 110, juz: [15,16],   pages: [293,304] },
  { number: 19,  name: "Maryam",          arabic: "مريم",        ayahs: 98,  juz: [16],      pages: [305,312] },
  { number: 20,  name: "Ta-Ha",           arabic: "طه",          ayahs: 135, juz: [16],      pages: [312,321] },
  { number: 21,  name: "Al-Anbiya",       arabic: "الأنبياء",    ayahs: 112, juz: [17],      pages: [322,331] },
  { number: 22,  name: "Al-Hajj",         arabic: "الحج",        ayahs: 78,  juz: [17],      pages: [332,341] },
  { number: 23,  name: "Al-Mu'minun",     arabic: "المؤمنون",    ayahs: 118, juz: [18],      pages: [342,349] },
  { number: 24,  name: "An-Nur",          arabic: "النور",       ayahs: 64,  juz: [18],      pages: [350,359] },
  { number: 25,  name: "Al-Furqan",       arabic: "الفرقان",     ayahs: 77,  juz: [18,19],   pages: [359,366] },
  { number: 26,  name: "Ash-Shu'ara",     arabic: "الشعراء",     ayahs: 227, juz: [19],      pages: [367,376] },
  { number: 27,  name: "An-Naml",         arabic: "النمل",       ayahs: 93,  juz: [19,20],   pages: [377,385] },
  { number: 28,  name: "Al-Qasas",        arabic: "القصص",       ayahs: 88,  juz: [20],      pages: [385,396] },
  { number: 29,  name: "Al-Ankabut",      arabic: "العنكبوت",    ayahs: 69,  juz: [20,21],   pages: [396,404] },
  { number: 30,  name: "Ar-Rum",          arabic: "الروم",       ayahs: 60,  juz: [21],      pages: [404,410] },
  { number: 31,  name: "Luqman",          arabic: "لقمان",       ayahs: 34,  juz: [21],      pages: [411,414] },
  { number: 32,  name: "As-Sajdah",       arabic: "السجدة",      ayahs: 30,  juz: [21],      pages: [415,417] },
  { number: 33,  name: "Al-Ahzab",        arabic: "الأحزاب",     ayahs: 73,  juz: [21,22],   pages: [418,427] },
  { number: 34,  name: "Saba",            arabic: "سبأ",         ayahs: 54,  juz: [22],      pages: [428,434] },
  { number: 35,  name: "Fatir",           arabic: "فاطر",        ayahs: 45,  juz: [22],      pages: [434,440] },
  { number: 36,  name: "Ya-Sin",          arabic: "يس",          ayahs: 83,  juz: [22,23],   pages: [440,445] },
  { number: 37,  name: "As-Saffat",       arabic: "الصافات",     ayahs: 182, juz: [23],      pages: [446,452] },
  { number: 38,  name: "Sad",             arabic: "ص",           ayahs: 88,  juz: [23],      pages: [452,458] },
  { number: 39,  name: "Az-Zumar",        arabic: "الزمر",       ayahs: 75,  juz: [23,24],   pages: [458,467] },
  { number: 40,  name: "Ghafir",          arabic: "غافر",        ayahs: 85,  juz: [24],      pages: [467,476] },
  { number: 41,  name: "Fussilat",        arabic: "فصلت",        ayahs: 54,  juz: [24,25],   pages: [477,482] },
  { number: 42,  name: "Ash-Shura",       arabic: "الشورى",      ayahs: 53,  juz: [25],      pages: [483,489] },
  { number: 43,  name: "Az-Zukhruf",      arabic: "الزخرف",      ayahs: 89,  juz: [25],      pages: [489,495] },
  { number: 44,  name: "Ad-Dukhan",       arabic: "الدخان",      ayahs: 59,  juz: [25],      pages: [496,498] },
  { number: 45,  name: "Al-Jathiyah",     arabic: "الجاثية",     ayahs: 37,  juz: [25],      pages: [499,502] },
  { number: 46,  name: "Al-Ahqaf",        arabic: "الأحقاف",     ayahs: 35,  juz: [26],      pages: [502,507] },
  { number: 47,  name: "Muhammad",        arabic: "محمد",        ayahs: 38,  juz: [26],      pages: [507,511] },
  { number: 48,  name: "Al-Fath",         arabic: "الفتح",       ayahs: 29,  juz: [26],      pages: [511,515] },
  { number: 49,  name: "Al-Hujurat",      arabic: "الحجرات",     ayahs: 18,  juz: [26],      pages: [515,517] },
  { number: 50,  name: "Qaf",             arabic: "ق",           ayahs: 45,  juz: [26],      pages: [518,520] },
  { number: 51,  name: "Adh-Dhariyat",    arabic: "الذاريات",    ayahs: 60,  juz: [26,27],   pages: [520,523] },
  { number: 52,  name: "At-Tur",          arabic: "الطور",       ayahs: 49,  juz: [27],      pages: [523,525] },
  { number: 53,  name: "An-Najm",         arabic: "النجم",       ayahs: 62,  juz: [27],      pages: [526,528] },
  { number: 54,  name: "Al-Qamar",        arabic: "القمر",       ayahs: 55,  juz: [27],      pages: [528,531] },
  { number: 55,  name: "Ar-Rahman",       arabic: "الرحمن",      ayahs: 78,  juz: [27],      pages: [531,534] },
  { number: 56,  name: "Al-Waqi'ah",      arabic: "الواقعة",     ayahs: 96,  juz: [27],      pages: [534,537] },
  { number: 57,  name: "Al-Hadid",        arabic: "الحديد",      ayahs: 29,  juz: [27],      pages: [537,541] },
  { number: 58,  name: "Al-Mujadila",     arabic: "المجادلة",    ayahs: 22,  juz: [28],      pages: [542,545] },
  { number: 59,  name: "Al-Hashr",        arabic: "الحشر",       ayahs: 24,  juz: [28],      pages: [545,548] },
  { number: 60,  name: "Al-Mumtahanah",   arabic: "الممتحنة",    ayahs: 13,  juz: [28],      pages: [549,551] },
  { number: 61,  name: "As-Saf",          arabic: "الصف",        ayahs: 14,  juz: [28],      pages: [551,552] },
  { number: 62,  name: "Al-Jumu'ah",      arabic: "الجمعة",      ayahs: 11,  juz: [28],      pages: [553,554] },
  { number: 63,  name: "Al-Munafiqun",    arabic: "المنافقون",   ayahs: 11,  juz: [28],      pages: [554,555] },
  { number: 64,  name: "At-Taghabun",     arabic: "التغابن",     ayahs: 18,  juz: [28],      pages: [556,557] },
  { number: 65,  name: "At-Talaq",        arabic: "الطلاق",      ayahs: 12,  juz: [28],      pages: [558,559] },
  { number: 66,  name: "At-Tahrim",       arabic: "التحريم",     ayahs: 12,  juz: [28],      pages: [560,561] },
  { number: 67,  name: "Al-Mulk",         arabic: "الملك",       ayahs: 30,  juz: [29],      pages: [562,564] },
  { number: 68,  name: "Al-Qalam",        arabic: "القلم",       ayahs: 52,  juz: [29],      pages: [564,566] },
  { number: 69,  name: "Al-Haqqah",       arabic: "الحاقة",      ayahs: 52,  juz: [29],      pages: [566,568] },
  { number: 70,  name: "Al-Ma'arij",      arabic: "المعارج",     ayahs: 44,  juz: [29],      pages: [568,570] },
  { number: 71,  name: "Nuh",             arabic: "نوح",         ayahs: 28,  juz: [29],      pages: [570,571] },
  { number: 72,  name: "Al-Jinn",         arabic: "الجن",        ayahs: 28,  juz: [29],      pages: [572,573] },
  { number: 73,  name: "Al-Muzzammil",    arabic: "المزمل",      ayahs: 20,  juz: [29],      pages: [574,575] },
  { number: 74,  name: "Al-Muddaththir",  arabic: "المدثر",      ayahs: 56,  juz: [29],      pages: [575,577] },
  { number: 75,  name: "Al-Qiyamah",      arabic: "القيامة",     ayahs: 40,  juz: [29],      pages: [577,578] },
  { number: 76,  name: "Al-Insan",        arabic: "الإنسان",     ayahs: 31,  juz: [29],      pages: [578,580] },
  { number: 77,  name: "Al-Mursalat",     arabic: "المرسلات",    ayahs: 50,  juz: [29],      pages: [580,581] },
  { number: 78,  name: "An-Naba",         arabic: "النبأ",       ayahs: 40,  juz: [30],      pages: [582,583] },
  { number: 79,  name: "An-Nazi'at",      arabic: "النازعات",    ayahs: 46,  juz: [30],      pages: [583,584] },
  { number: 80,  name: "Abasa",           arabic: "عبس",         ayahs: 42,  juz: [30],      pages: [585,585] },
  { number: 81,  name: "At-Takwir",       arabic: "التكوير",     ayahs: 29,  juz: [30],      pages: [586,586] },
  { number: 82,  name: "Al-Infitar",      arabic: "الانفطار",    ayahs: 19,  juz: [30],      pages: [587,587] },
  { number: 83,  name: "Al-Mutaffifin",   arabic: "المطففين",    ayahs: 36,  juz: [30],      pages: [587,589] },
  { number: 84,  name: "Al-Inshiqaq",     arabic: "الانشقاق",    ayahs: 25,  juz: [30],      pages: [589,589] },
  { number: 85,  name: "Al-Buruj",        arabic: "البروج",      ayahs: 22,  juz: [30],      pages: [590,591] },
  { number: 86,  name: "At-Tariq",        arabic: "الطارق",      ayahs: 17,  juz: [30],      pages: [591,591] },
  { number: 87,  name: "Al-A'la",         arabic: "الأعلى",      ayahs: 19,  juz: [30],      pages: [591,592] },
  { number: 88,  name: "Al-Ghashiyah",    arabic: "الغاشية",     ayahs: 26,  juz: [30],      pages: [592,592] },
  { number: 89,  name: "Al-Fajr",         arabic: "الفجر",       ayahs: 30,  juz: [30],      pages: [593,594] },
  { number: 90,  name: "Al-Balad",        arabic: "البلد",       ayahs: 20,  juz: [30],      pages: [594,594] },
  { number: 91,  name: "Ash-Shams",       arabic: "الشمس",       ayahs: 15,  juz: [30],      pages: [595,595] },
  { number: 92,  name: "Al-Layl",         arabic: "الليل",       ayahs: 21,  juz: [30],      pages: [595,596] },
  { number: 93,  name: "Ad-Duha",         arabic: "الضحى",       ayahs: 11,  juz: [30],      pages: [596,596] },
  { number: 94,  name: "Ash-Sharh",       arabic: "الشرح",       ayahs: 8,   juz: [30],      pages: [596,596] },
  { number: 95,  name: "At-Tin",          arabic: "التين",       ayahs: 8,   juz: [30],      pages: [597,597] },
  { number: 96,  name: "Al-Alaq",         arabic: "العلق",       ayahs: 19,  juz: [30],      pages: [597,598] },
  { number: 97,  name: "Al-Qadr",         arabic: "القدر",       ayahs: 5,   juz: [30],      pages: [598,598] },
  { number: 98,  name: "Al-Bayyinah",     arabic: "البينة",      ayahs: 8,   juz: [30],      pages: [598,599] },
  { number: 99,  name: "Az-Zalzalah",     arabic: "الزلزلة",     ayahs: 8,   juz: [30],      pages: [599,599] },
  { number: 100, name: "Al-Adiyat",       arabic: "العاديات",    ayahs: 11,  juz: [30],      pages: [599,600] },
  { number: 101, name: "Al-Qari'ah",      arabic: "القارعة",     ayahs: 11,  juz: [30],      pages: [600,600] },
  { number: 102, name: "At-Takathur",     arabic: "التكاثر",     ayahs: 8,   juz: [30],      pages: [600,600] },
  { number: 103, name: "Al-Asr",          arabic: "العصر",       ayahs: 3,   juz: [30],      pages: [601,601] },
  { number: 104, name: "Al-Humazah",      arabic: "الهمزة",      ayahs: 9,   juz: [30],      pages: [601,601] },
  { number: 105, name: "Al-Fil",          arabic: "الفيل",       ayahs: 5,   juz: [30],      pages: [601,601] },
  { number: 106, name: "Quraysh",         arabic: "قريش",        ayahs: 4,   juz: [30],      pages: [602,602] },
  { number: 107, name: "Al-Ma'un",        arabic: "الماعون",     ayahs: 7,   juz: [30],      pages: [602,602] },
  { number: 108, name: "Al-Kawthar",      arabic: "الكوثر",      ayahs: 3,   juz: [30],      pages: [602,602] },
  { number: 109, name: "Al-Kafirun",      arabic: "الكافرون",    ayahs: 6,   juz: [30],      pages: [603,603] },
  { number: 110, name: "An-Nasr",         arabic: "النصر",       ayahs: 3,   juz: [30],      pages: [603,603] },
  { number: 111, name: "Al-Masad",        arabic: "المسد",       ayahs: 5,   juz: [30],      pages: [603,603] },
  { number: 112, name: "Al-Ikhlas",       arabic: "الإخلاص",    ayahs: 4,   juz: [30],      pages: [604,604] },
  { number: 113, name: "Al-Falaq",        arabic: "الفلق",       ayahs: 5,   juz: [30],      pages: [604,604] },
  { number: 114, name: "An-Nas",          arabic: "الناس",       ayahs: 6,   juz: [30],      pages: [604,604] },
]

export const JUZ = [
  { number: 1,  name: "Alif Lam Mim",       startPage: 1,   endPage: 21  },
  { number: 2,  name: "Sayaqool",            startPage: 22,  endPage: 41  },
  { number: 3,  name: "Tilkal Rusul",        startPage: 42,  endPage: 61  },
  { number: 4,  name: "Lan Tanaloo",         startPage: 62,  endPage: 81  },
  { number: 5,  name: "Wal Mohsanat",        startPage: 82,  endPage: 101 },
  { number: 6,  name: "La Yuhibbullah",      startPage: 102, endPage: 121 },
  { number: 7,  name: "Wa Iza Sami'oo",      startPage: 122, endPage: 141 },
  { number: 8,  name: "Wa Law Annana",       startPage: 142, endPage: 161 },
  { number: 9,  name: "Qalal Mala",          startPage: 162, endPage: 181 },
  { number: 10, name: "Wa A'lamoo",          startPage: 182, endPage: 201 },
  { number: 11, name: "Yatazeroon",          startPage: 202, endPage: 221 },
  { number: 12, name: "Wa Ma Min Dabbah",    startPage: 222, endPage: 241 },
  { number: 13, name: "Wa Ma Ubarrio",       startPage: 242, endPage: 261 },
  { number: 14, name: "Rubama",              startPage: 262, endPage: 281 },
  { number: 15, name: "Subhanallazi",        startPage: 282, endPage: 301 },
  { number: 16, name: "Qal Alam",            startPage: 302, endPage: 321 },
  { number: 17, name: "Iqtaraba",            startPage: 322, endPage: 341 },
  { number: 18, name: "Qad Aflaha",          startPage: 342, endPage: 361 },
  { number: 19, name: "Wa Qalallazina",      startPage: 362, endPage: 381 },
  { number: 20, name: "Amman Khalaq",        startPage: 382, endPage: 401 },
  { number: 21, name: "Utlu Ma Oohi'a",      startPage: 402, endPage: 421 },
  { number: 22, name: "Wa Man Yaqnut",       startPage: 422, endPage: 441 },
  { number: 23, name: "Wa Mali",             startPage: 442, endPage: 461 },
  { number: 24, name: "Faman Azlam",         startPage: 462, endPage: 481 },
  { number: 25, name: "Ilayhi Yuraddu",      startPage: 482, endPage: 501 },
  { number: 26, name: "Ha Meem",             startPage: 502, endPage: 521 },
  { number: 27, name: "Qala Fama Khatbukum", startPage: 522, endPage: 541 },
  { number: 28, name: "Qad Sami'allah",      startPage: 542, endPage: 561 },
  { number: 29, name: "Tabarakal Lazi",      startPage: 562, endPage: 581 },
  { number: 30, name: "Amma Yatasa'aloon",   startPage: 582, endPage: 604 },
]

export const TOTAL_PAGES = 604

export const MOTIVATIONAL_QUOTES = [
  { arabic: "وَلَقَدْ يَسَّرْنَا الْقُرْآنَ لِلذِّكْرِ فَهَلْ مِن مُّدَّكِرٍ", english: "And We have certainly made the Quran easy to remember. So is there anyone who will remember? — Al-Qamar 54:17" },
  { arabic: "إِنَّ الَّذِينَ يَتْلُونَ كِتَابَ اللَّهِ وَأَقَامُوا الصَّلَاةَ", english: "Indeed, those who recite the Book of Allah and establish prayer — Al-Fatir 35:29" },
  { arabic: "وَرَتِّلِ الْقُرْآنَ تَرْتِيلًا", english: "And recite the Quran with measured recitation. — Al-Muzzammil 73:4" },
  { arabic: "فَإِذَا قَرَأْتَ الْقُرْآنَ فَاسْتَعِذْ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ", english: "So when you recite the Quran, seek refuge in Allah from the outcast Satan. — An-Nahl 16:98" },
  { arabic: "أَفَلَا يَتَدَبَّرُونَ الْقُرْآنَ أَمْ عَلَىٰ قُلُوبٍ أَقْفَالُهَا", english: "Do they not reflect on the Quran, or are there locks upon their hearts? — Muhammad 47:24" },
  { arabic: "كِتَابٌ أَنزَلْنَاهُ إِلَيْكَ مُبَارَكٌ لِّيَدَّبَّرُوا آيَاتِهِ", english: "A blessed Book which We have revealed to you, that they might reflect upon its verses. — Sad 38:29" },
  { arabic: "إِنَّ هَٰذَا الْقُرْآنَ يَهْدِي لِلَّتِي هِيَ أَقْوَمُ", english: "Indeed, this Quran guides to that which is most suitable — Al-Isra 17:9" },
  { arabic: "وَنُنَزِّلُ مِنَ الْقُرْآنِ مَا هُوَ شِفَاءٌ وَرَحْمَةٌ لِّلْمُؤْمِنِينَ", english: "And We send down the Quran as healing and mercy for the believers. — Al-Isra 17:82" },
]

export function getSurahByNumber(n) {
  return SURAHS.find(s => s.number === n)
}

export function getPageForSurah(surahNum) {
  const s = getSurahByNumber(surahNum)
  return s ? s.pages[0] : 1
}

export function getJuzForPage(page) {
  return JUZ.find(j => page >= j.startPage && page <= j.endPage) || JUZ[0]
}
